{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-26T06:26:00.000Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-26T06:26:00.012Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-26T06:26:00.012Z"}
