{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoError","stack":"MongoError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-11-09T11:42:39.435Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoError","stack":"MongoError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-11-09T11:42:39.445Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoError","stack":"MongoError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-11-09T11:42:39.454Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoError","stack":"MongoError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-11-09T15:31:51.108Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoError","stack":"MongoError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-11-09T15:31:51.141Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoError","stack":"MongoError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-11-09T15:31:51.156Z"}
